### ISSUE TITLE
How is questData.json generated?

### ISSUE THREAD

**Issue by tha23rd** [cerniglj1/osrs-quest-tool#3]
Hi, would you consider open sourcing the tool you use to generate your data JSON files?

**Comment by cerniglj1** [comment]
Hey tha23rd!
I actually do not have a tool that scrapes the wiki or anything. I manually created that json by going through each quest.
Do you have any ideas of a tool that should be able to do this? possibly a python script to iterate through the wiki pages?

Feel free to reach out to me anytime and If there is any data that is incorrect please let me know.

**Comment by cerniglj1** [comment]
Created Quest Data Generation project to resolve this.

Python script that gets all current quests from url and will parse each individually. It's a WIP.

**Comment by Evaldash** [comment]
Hi, is the tool working? If so, would you mind sharing the link?

**Comment by jamescer** [comment]
@Evaldash Hey sorry for the late response. I just published a branch 'dev', inside I updated [the python file](https://github.com/jamescer/osrs-tools/blob/dev/tools/getQuestData.py ) used to grab all the quest data.
Let me know if this answers your question, I have to make a couple of parsing updates
